### ISSUE TITLE
Cannot build with python 3.8.5

### ISSUE THREAD

**Issue by nolash** [blocknetdx/documentation#17]
building with python 3.8.5 fails. The `README.md` suggests python support up to 3.7 inclusive, but posting this anyway in case that's an artifact from pre-3.8 times. 

I don't know the `mkdocs` tool at all, but nonetheless I tried manually to remove the `page.meta` references in `main.html`, which eliminates errors but command just exits and docs are not served.

---

```
$ mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - -dashboard.md
  - -support.md
  - -tools.md
  - -contributing/community.md
  - -contributing/developers.md
  - -developers/blockchain-integration.md
  - -developers/project-ideas.md
  - -developers/repositories.md
  - -developers/service-integration.md
  - -developers/tools.md
  - blockdx/-settings.md
  - blockdx/-troubleshooting.md
  - blockdx/-updating.md
  - blockdx/-setup/create-legacy-address.md
  - blockdx/-setup/view-inputs.md
  - governance/-blocknet-improvement-process-bip.md
  - governance/-governance-model.md
  - project/faq.md
  - proposals/coin-split-100-1.md
  - proposals/project-funding.md
  - proposals/single-tier-block-reward.md
  - wallet/-address-balances.md
  - wallet/-addresses.md
  - wallet/-backup-restore.md
  - wallet/-balances.md
  - wallet/-coin-control.md
  - wallet/-create-inputs.md
  - wallet/-debug-console.md
  - wallet/-peers.md
  - wallet/-security.md
  - wallet/-send-funds.md
  - wallet/-transaction-details.md
  - wallet/-troubleshooting.md
  - wallet/-updating.md 
WARNING -  A relative path to 'protocol/xrouter/introduction/#fees' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'protocol/xrouter/introduction/#design' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'protocol/xrouter/introduction/#use-cases' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'protocol/xrouter/introduction/#fees' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'protocol/xrouter/introduction/#design' is included in the 'nav' configuration, which is not found in the documentation files 
Traceback (most recent call last):
  File "/home/lash/src/ext/defi/documentation/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 87, in _build_template
    output = template.render(context)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/home/lash/src/ext/defi/documentation/theme/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/material/base.html", line 34, in top-level template code
    {% block htmltitle %}
  File "/home/lash/src/ext/defi/documentation/theme/main.html", line 5, in block "htmltitle"
    <title>{% if page.meta.title %}{{ page.meta.title }}{% elif page.title %}{{ page.title }} - {{ config.site_name }}{% else %}{{ config.site_name }}{% endif %}</title>
  File "/home/lash/src/ext/defi/documentation/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'meta'

$ pip freeze
click==7.1.2
fontawesome-markdown==0.2.6
future==0.18.2
Jinja2==2.11.2
joblib==0.16.0
livereload==2.6.3
lunr==0.5.8
Markdown==3.2.2
markdown-meta-extension==0.5.3
MarkupSafe==1.1.1
mkdocs==1.1.2
mkdocs-material==5.5.12
mkdocs-material-extensions==1.0
nltk==3.5
pathvalidate==2.3.0
Pygments==2.7.1
pymdown-extensions==8.0
PyYAML==5.3.1
regex==2020.7.14
six==1.15.0
tornado==6.0.4
tqdm==4.49.0
```

**Comment by ConanMishler** [comment]
I'm getting this exact same error log when I try to build this. I've tried building with python 3.5.10, 3.6.0, 3.7.0, 3.7.3. All of those versions of python are supposedly supported, but I'm still getting the exact same error log posted by nolash. Somehow the "page" object is set to "None" - thus the error when python tries to reference the attributes of the page object.

**Comment by ConanMishler** [comment]
I found a way to get the docs to build without error. The ReadME instructions say, `pip install mkdocs-material` but it should say, `pip install mkdocs-material==4.6.3`. Then the docs are built without error. I'll update the ReadME in a bit.

**Comment by luusluus** [comment]
I have improved the getting started section. Now it is encouraged to use a virtual environment. 

I have tested this for python versions 3.7 and 3.8 and these work.
